CREATE INDEX index_maintable_subject_id ON %s.maintable(subject_id);
CREATE INDEX index_maintable_predicate_id ON %s.maintable(predicate_id);
CREATE INDEX index_maintable_tuple_id ON %s.maintable(tuple_id);
CREATE INDEX index_maintable_internallink_id ON %s.maintable(internallink_id);
CREATE INDEX index_maintable_normalizedpattern_id ON %s.maintable(normalizedpattern_id);
CREATE INDEX index_maintable_pattern_id ON %s.maintable(pattern_id);
CREATE INDEX index_maintable_datatype_id ON %s.maintable(datatype_id);
CREATE INDEX index_maintable_parsed_value ON %s.maintable(parsed_value);
CREATE INDEX index_maintable_subject_internallink ON %s.maintable(subject_id, internallink_id);
CREATE INDEX index_maintable_subject_predicate ON %s.maintable(subject_id, predicate_id);
CREATE INDEX index_maintable_subject_internallink_predicate ON %s.maintable(subject_id, internallink_id, predicate_id);
CREATE INDEX index_maintable_subject_internallink_predicate_datatype ON %s.maintable(subject_id, internallink_id, predicate_id, datatype_id);
CREATE INDEX index_maintable_subject_predicate_datatype ON %s.maintable(subject_id, predicate_id, datatype_id);
CREATE INDEX index_maintable_subject_predicate_datatype_normalizedpattern ON %s.maintable(subject_id, predicate_id, datatype_id, normalizedpattern_id);
CREATE INDEX index_maintable_subject_predicate_datatype_pattern ON %s.maintable(subject_id, predicate_id, datatype_id, pattern_id);
CREATE INDEX index_maintable_subject_predicate_datatype_normpat_pattern ON %s.maintable(subject_id, predicate_id, datatype_id, normalizedpattern_id, pattern_id);
CREATE INDEX index_maintable_subject_pred_datat_normpat_pattern_parsedv ON %s.maintable(subject_id, predicate_id, datatype_id, normalizedpattern_id, pattern_id, parsed_value);
CREATE INDEX index_maintable_subject_predicate_datatype_pattern_parsedvalue ON %s.maintable(subject_id, predicate_id, datatype_id, pattern_id, parsed_value);
CREATE INDEX index_maintable_subject_predicate_datatype_parsedvalue ON %s.maintable(subject_id, predicate_id, datatype_id, parsed_value);
CREATE INDEX index_maintable_subject_predicate_parsedvalue ON %s.maintable(subject_id, predicate_id, parsed_value);
CREATE INDEX index_maintable_subject_predicate_datatype_tuple ON %s.maintable(subject_id, predicate_id, datatype_id, tuple_id);
CREATE INDEX index_maintable_subject_predicate_normalizedpattern_datatype ON %s.maintable(subject_id, predicate_id, normalizedpattern_id, datatype_id);
CREATE INDEX index_maintable_subject_predicate_pattern_datatype ON %s.maintable(subject_id, predicate_id, pattern_id, datatype_id);
CREATE INDEX index_maintable_SubjPredPattNormpattDatetype ON %s.maintable(subject_id, predicate_id, pattern_id, normalizedpattern_id, datatype_id);
CREATE INDEX index_maintable_subject_predicate_tuple_datatype ON %s.maintable(subject_id, predicate_id, tuple_id, datatype_id);
CREATE INDEX index_maintable_subject_predicate_tuple_normpattern_datatype ON %s.maintable(subject_id, predicate_id, tuple_id, normalizedpattern_id, datatype_id);
CREATE INDEX index_maintable_subject_predicate_tuple_pattern_datatype ON %s.maintable(subject_id, predicate_id, tuple_id, pattern_id, datatype_id);
CREATE INDEX index_maintable_predicate_normalizedpattern_datatype ON %s.maintable(predicate_id, normalizedpattern_id, datatype_id);
CREATE INDEX index_maintable_predicate_pattern_datatype ON %s.maintable(predicate_id, pattern_id, datatype_id);
CREATE INDEX index_maintable_predicate_tuple_datatype ON %s.maintable(predicate_id, tuple_id, datatype_id);
CREATE INDEX index_maintable_predicate_tuple_normalizedpattern_datatype ON %s.maintable(predicate_id, tuple_id, normalizedpattern_id, datatype_id);
CREATE INDEX index_maintable_predicate_tuple_pattern_datatype ON %s.maintable(predicate_id, tuple_id, pattern_id, datatype_id);