-- Creates a new cluster
-- %1$s the source user view
-- %2$s the new user view

INSERT INTO CLUSTERS_WRITABLE
			(ID, SESSION_ID, SESSION_LOCAL_ID, LABEL, CLUSTER_SIZE, CHILD_SESSION, AVG_ERROR, PARTITIONNAME, USERNAME)  
	(SELECT  ID, SESSION_ID, SESSION_LOCAL_ID, LABEL, CLUSTER_SIZE, CHILD_SESSION, AVG_ERROR, PARTITIONNAME, '%2$s'
		FROM CLUSTERS
			WHERE USERNAME = '%1$s')