-- create cluster tables
-- %1$s default user
	
create table CLUSTER_SESSIONS (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255),
	PRIMARY KEY(ID));

	
create table CLUSTERS (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(50) NOT NULL DEFAULT '%1$s',
  	SESSION_ID INT UNSIGNED NOT NULL,
  	SESSION_LOCAL_ID INT UNSIGNED,
  	LABEL VARCHAR (255),
  	CHILD_SESSION INT UNSIGNED,
  	AVG_ERROR FLOAT,
  	CLUSTER_SIZE INT UNSIGNED,
  	PARTITIONNAME VARCHAR (255) NOT NULL DEFAULT 'maintable',
  	primary key (ID, USERNAME),
  	foreign key (SESSION_ID) references CLUSTER_SESSIONS (ID) on delete cascade);

-- create indices
CREATE INDEX INDEX_CLUSTER_SESSIONS_NAME ON CLUSTER_SESSIONS(NAME);
CREATE INDEX INDEX_CLUSTERS_SESSION_ID ON CLUSTERS(SESSION_ID);
CREATE INDEX INDEX_CLUSTERS_CHILD_SESSION ON CLUSTERS(CHILD_SESSION);

  	
create table CLUSTER_SUBJECTS (
	CLUSTER_ID INT UNSIGNED NOT NULL,
	subject_id INT UNSIGNED NOT NULL,
	primary key (CLUSTER_ID, subject_id)
	);
--	, foreign key (CLUSTER_ID) references CLUSTERS(ID) on delete cascade

-- create indices
CREATE INDEX INDEX_CLUSTER_SUBJECTS_CLUSTER_ID ON CLUSTER_SUBJECTS(CLUSTER_ID);
CREATE INDEX INDEX_CLUSTER_SUBJECTS_SUBJECT_CLUSTER ON CLUSTER_SUBJECTS(subject_id, CLUSTER_ID);

	
create table CLUSTER_MEANSCHEMA (
	CLUSTER_ID INT UNSIGNED NOT NULL,
	predicate_id INT UNSIGNED NOT NULL,
	RANK INT UNSIGNED
	);
--	, foreign key (CLUSTER_ID) references CLUSTERS(ID) on delete cascade

-- create indices
CREATE INDEX INDEX_CLUSTER_MEANSCHEMA_CLUSTER_ID ON CLUSTER_MEANSCHEMA(CLUSTER_ID);
CREATE INDEX INDEX_CLUSTER_MEANSCHEMA_CLUSTER_ID_PREDICATE_ID ON CLUSTER_MEANSCHEMA(CLUSTER_ID,predicate_id);
