


create table OntologyRemovals (
	ID INT GENERATED BY DEFAULT AS IDENTITY,
  	C_ID INT NOT NULL,
  	S_ID INT NOT NULL,
  	removedProperty INT);
  	
  	
create table OntologyAddition (
	ID INT GENERATED BY DEFAULT AS IDENTITY,
  	C_ID INT NOT NULL,
  	S_ID INT NOT NULL,
  	addedProperty INT,
  	source_C_ID INT);



CREATE INDEX INDEX_Ontology_Class_ID ON OntologyRemovals(C_ID);




CREATE INDEX INDEX_Subject_Class_ID ON OntologyRemovals(S_ID);

CREATE INDEX INDEX_Ontology_Class_INC_ID ON OntologyAddition(C_ID);




CREATE INDEX INDEX_Subject_Class_INC_ID ON OntologyAddition(S_ID);