CREATE TABLE %s.MAINTABLE
(
    SUBJECT_ID INT,
    PREDICATE_ID INT,
    INTERNALLINK_ID INT,
    DATATYPE_ID INT,
    NORMALIZEDPATTERN_ID INT,
    PATTERN_ID INT,
    PARSED_VALUE FLOAT(53),
    TUPLE_ID INT
)